version: "3"
services:
  node-app:
    build: .
    depends_on:
      - postgis
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

    postgis:
      image: postgis
      ports:
      - "35432:5432"
      environment:
        POSTGRES_USER: ppraxis
        POSTGRES_PASSWORD: testing
        POSTGRES_DB: db